on:
  push:
    branches:
      - master

name: Deploy

jobs:
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' || github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build container'
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: 'ghcr.io/dcnick3/my-website:ref-${{ github.sha }}'
          cache-from: type=registry,ref=ghcr.io/dcnick3/my-website:buildcache
          cache-to: type=registry,ref=ghcr.io/dcnick3/my-website:buildcache,mode=max

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://my-website.dcnick3.me
    steps:
      - uses: actions/checkout@v1

      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - uses: Azure/k8s-deploy@v3.1
        with:
          namespace: 'default'
          manifests: |
            deployment
          images: 'ghcr.io/dcnick3/my-website:ref-${{ github.sha }}'